=== martin-ottens/proto2testbed/controller/assets/config.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "config.schema.json",
    "title": "Proto-Testbed Config",
    "description": "Testbed config for a Proto-Testbed setup package",
    "type": "object",
    "properties": {
        "settings": {
            "type": "object",
            "properties": {
                "management_network": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "diskimage_basepath": {
                    "type": "string"
                },
                "startup_init_timeout": {
                    "type": "number"
                },
                "experiment_timeout": {
                    "type": "number"
                }
            },
            "additionalItems": false
        },
        "networks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "host_ports": {
                        "type": "array",
                        "items": {
                            "type": [
                                "string",
                                "null"
                            ]
                        }
                    }
                },
                "additionalItems": false,
                "required": [
                    "name",
                    "host_ports"
                ]
            }
        },
        "integrations": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "environment": {
                        "type": [
                            "object",
                            "null"
                        ]
                    },
                    "invoke_after": {
                        "type": "string",
                        "enum": [
                            "startup",
                            "network",
                            "init"
                        ]
                    },
                    "wait_after_invoke": {
                        "type": "number"
                    },
                    "settings": {
                        "type": "object"
                    }
                },
                "additionalItems": false,
                "required": [
                    "name",
                    "type",
                    "invoke_after",
                    "settings"
                ]
            }
        },
        "instances": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "diskimage": {
                        "type": "string"
                    },
                    "setup_script": {
                        "type": [
                            "string",
                            "null"
                        ]
                    },
                    "environment": {
                        "type": [
                            "object",
                            "null"
                        ]
                    },
                    "cores": {
                        "type": "number"
                    },
                    "memory": {
                        "type": "number"
                    },
                    "networks": {
                        "oneOf": [
                            {
                                "type": "null"
                            },
                            {
                                "type": "array",
                                "items": {
                                    "oneOf": [
                                        {
                                            "type": "string"
                                        },
                                        {
                                            "type": "object",
                                            "properties": {
                                                "name": {
                                                    "type": "string"
                                                },
                                                "mac": {
                                                    "type": "string"
                                                },
                                                "netmodel": {
                                                    "type": "string",
                                                    "enum": [
                                                        "virtio",
                                                        "e1000",
                                                        "rtl8139"
                                                    ]
                                                }
                                            },
                                            "required": [
                                                "name"
                                            ],
                                            "additionalItems": false
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "preserve_files": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "applications": {
                        "type": [
                            "array",
                            "null"
                        ],
                        "items": {
                            "type": "object",
                            "properties": {
                                "application": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                },
                                "delay": {
                                    "type": "number"
                                },
                                "runtime": {
                                    "type": ["number", "null"]
                                },
                                "dont_store": {
                                    "type": "boolean"
                                },
                                "load_from_instance": {
                                    "type": "boolean"
                                },
                                "settings": {
                                    "type": "object"
                                }
                            },
                            "required": [
                                "application",
                                "name",
                                "runtime",
                                "settings"
                            ],
                            "additionalItems": false
                        }
                    }
                },
                "additionalItems": false,
                "required": [
                    "name",
                    "diskimage",
                    "setup_script",
                    "environment",
                    "networks",
                    "applications"
                ]
            }
        }
    },
    "required": [
        "settings",
        "networks",
        "integrations",
        "instances"
    ],
    "additionalItems": false
}

=== martin-ottens/proto2testbed/setups/example1/testbed.json
{
    "settings": {
        "management_network": "172.16.99.0/24",
        "diskimage_basepath": "/images/"
    },
    "networks": [
        {
            "name": "exp0",
            "host_ports": []
        },
        {
            "name": "exp1",
            "host_ports": []
        }
    ],
    "integrations": [],
    "instances": [
        {
            "name": "a-endpoint",
            "diskimage": "{{IMAGE_ENDPOINT}}",
            "setup_script": "endpoint/setup.sh",
            "environment": {
                "IP_ADDRESS": "10.0.1.1/24",
                "ROUTE": "10.0.2.0/24 via 10.0.1.2",
                "WIREGUARD": "{{WIREGUARD_A}}"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp0"
            ],
            "applications": [
                {
                    "application": "iperf3-server",
                    "name": "a-iperf-server",
                    "delay": 0,
                    "runtime": null,
                    "settings": {}
                },
                {
                    "application": "procmon",
                    "name": "a-procmon",
                    "delay": 5,
                    "runtime": 60,
                    "settings": {
                        "interfaces": ["eth1"],
                        "system": false
                    }
                }
            ]
        },
        {
            "name": "router",
            "diskimage": "{{IMAGE_ROUTER}}",
            "setup_script": "router/setup.sh",
            "environment": {
                "IP_ADDRESS_0": "10.0.1.2/24",
                "IP_ADDRESS_1": "10.0.2.2/24"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp0",
                "exp1"
            ],
            "applications": [
                {
                    "application": "run-program",
                    "name": "add_delay",
                    "delay": 30,
                    "runtime": null,
                    "settings": {
                        "command": "router/application.sh",
                        "ignore_timeout": true,
                        "environment": {
                            "INTERFACE": "eth1",
                            "DELAY_MS": 100
                        }
                    }
                }
            ]
        },
        {
            "name": "b-endpoint",
            "diskimage": "{{IMAGE_ENDPOINT}}",
            "setup_script": "endpoint/setup.sh",
            "environment": {
                "IP_ADDRESS": "10.0.2.1/24",
                "ROUTE": "10.0.1.0/24 via 10.0.2.2",
                "WIREGUARD": "{{WIREGUARD_B}}"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp1"
            ],
            "applications": [
                {
                    "application": "iperf3-client",
                    "name": "b-iperf-client",
                    "delay": 1,
                    "runtime": 60,
                    "settings": {
                        "host": "{{IPERF_HOST}}"
                    }
                },
                {
                    "application": "ping",
                    "name": "b-ping",
                    "delay": 10,
                    "runtime": 60,
                    "settings": {
                        "target": "{{PING_TARGET}}",
                        "source": "{{PING_SOURCE}}"
                    }
                }
            ]
        }
    ]
}

=== martin-ottens/proto2testbed/setups/example3/testbed.json
{
    "settings": {
        "management_network": "172.16.99.0/24",
        "diskimage_basepath": "/tmp"
    },
    "networks": [
        {
            "name": "exp0",
            "host_ports": [
                "eno2"
            ]
        },
        {
            "name": "exp1",
            "host_ports": [
                "eno3"
            ]
        }
    ],
    "integrations": [
        {
            "name": "prepare interfaces",
            "type": "startstop",
            "invoke_after": "network",
            "environment": {
                "INTERFACE_A": "eno2",
                "INTERFACE_B": "eno3"
            },
            "settings": {
                "start_script": "integrations/ifup.sh",
                "stop_script": "integrations/ifdown.sh"

            }
        },
        {
            "name": "exp0 link to 100mbits",
            "type": "startstop",
            "invoke_after": "init",
            "wait_after_invoke": 0,
            "environment": {
                "INTERFACE": "eno2"
            },
            "settings": {
                "start_script": "integrations/setspeed.sh",
                "stop_script": "integrations/resetspeed.sh",
                "start_delay": 20
            }
        },
        {
            "name": "exp1 link to 100mbits",
            "type": "startstop",
            "invoke_after": "init",
            "wait_after_invoke": 0,
            "environment": {
                "INTERFACE": "eno3"
            },
            "settings": {
                "start_script": "integrations/setspeed.sh",
                "stop_script": "integrations/resetspeed.sh",
                "start_delay": 40
            }
        }
    ],
    "instances": [
        {
            "name": "a1-endpoint",
            "diskimage": "endpoint.qcow2",
            "setup_script": "endpoint/setup.sh",
            "environment": {
                "IP_ADDRESS": "10.0.1.2/24",
                "ROUTE": "10.0.2.0/24 via 10.0.1.1"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp0"
            ],
            "applications": [
                {
                    "application": "iperf3-server",
                    "name": "a1-iperf-server",
                    "delay": 0,
                    "runtime": null,
                    "settings": {}
                }
            ]
        },
        {
            "name": "a2-endpoint",
            "diskimage": "endpoint.qcow2",
            "setup_script": "endpoint/setup.sh",
            "environment": {
                "IP_ADDRESS": "10.0.1.3/24",
                "ROUTE": "10.0.2.0/24 via 10.0.1.1"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp0"
            ],
            "applications": [
                {
                    "application": "iperf3-server",
                    "name": "a2-iperf-server",
                    "delay": 0,
                    "runtime": null,
                    "settings": {}
                },
                {
                    "application": "ping",
                    "name": "b2-a1-ping",
                    "delay": 2,
                    "runtime": 75,
                    "settings": {
                        "target": "10.0.2.3"
                    }
                }
            ]
        },
        {
            "name": "b1-endpoint",
            "diskimage": "endpoint.qcow2",
            "setup_script": "endpoint/setup.sh",
            "environment": {
                "IP_ADDRESS": "10.0.2.2/24",
                "ROUTE": "10.0.1.0/24 via 10.0.2.1"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp1"
            ],
            "applications": [
                {
                    "application": "iperf3-client",
                    "name": "b1-iperf-client",
                    "delay": 5,
                    "runtime": 60,
                    "settings": {
                        "host": "10.0.1.3"
                    }
                },
                {
                    "application": "ping",
                    "name": "b1-a2-ping",
                    "delay": 2,
                    "runtime": 75,
                    "settings": {
                        "target": "10.0.1.2"
                    }
                }
            ]
        },
        {
            "name": "b2-endpoint",
            "diskimage": "endpoint.qcow2",
            "setup_script": "endpoint/setup.sh",
            "environment": {
                "IP_ADDRESS": "10.0.2.3/24",
                "ROUTE": "10.0.1.0/24 via 10.0.2.1"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp1"
            ],
            "applications": [
                {
                    "application": "iperf3-client",
                    "name": "b2-iperf-client",
                    "delay": 10,
                    "runtime": 60,
                    "settings": {
                        "host": "10.0.1.2"
                    }
                }
            ]
        }
    ]
}

=== martin-ottens/proto2testbed/setups/example2/testbed.json
{
    "settings": {
        "management_network": "172.16.99.0/24",
        "diskimage_basepath": "/tmp"
    },
    "networks": [
        {
            "name": "exp0",
            "host_ports": [
                "ns3_em0"
            ]
        },
        {
            "name": "exp1",
            "host_ports": [
                "ns3_em1"
            ]
        }
    ],
    "integrations": [
        {
            "type": "ns3-emulation",
            "name": "run-ns3",
            "invoke_after": "startup",
            "wait_after_invoke": 3,
            "settings": {
                "basepath": "/tmp/ns-3-dev",
                "program": "emulator",
                "wait": true,
                "fail_on_exist": true,
                "interfaces": [
                    "ns3_em0",
                    "ns3_em1"
                ],
                "args": {
                    "routers": "{{ROUTERS}}"
                }
            }
        }
    ],
    "instances": [
        {
            "name": "a-endpoint",
            "diskimage": "endpoint.qcow2",
            "setup_script": "endpoint/setup.sh",
            "environment": {
                "IP_ADDRESS": "172.20.0.2/24",
                "ROUTE": "172.20.{{ROUTERS}}.0/24 via 172.20.0.1"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp0"
            ],
            "applications": [
                {
                    "application": "iperf3-server",
                    "name": "a-iperf-server",
                    "delay": 0,
                    "runtime": null,
                    "settings": {}
                }
            ]
        },
        {
            "name": "b-endpoint",
            "diskimage": "endpoint.qcow2",
            "setup_script": "endpoint/setup.sh",
            "environment": {
                "IP_ADDRESS": "172.20.{{ROUTERS}}.2/24",
                "ROUTE": "172.20.0.0/24 via 172.20.{{ROUTERS}}.1"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp1"
            ],
            "applications": [
                {
                    "application": "iperf3-client",
                    "name": "b-iperf-client",
                    "delay": 5,
                    "runtime": 60,
                    "settings": {
                        "host": "172.20.0.2"
                    }
                },
                {
                    "application": "ping",
                    "name": "b-ping",
                    "delay": 0,
                    "runtime": 65,
                    "settings": {
                        "target": "172.20.0.2"
                    }
                }
            ]
        }
    ]
}

=== martin-ottens/proto2testbed/setups/api/testbed.json
{
    "settings": {
        "management_network": "auto",
        "diskimage_basepath": "/images"
    },
    "networks": [
        {
            "name": "link_a",
            "host_ports": []
        }
    ],
    "integrations": [],
    "instances": [
        {
            "name": "vma",
            "diskimage": "debian-iperf.qcow2",
            "setup_script": "setup.sh",
            "environment": {
                "IP_ADDRESS": "10.0.0.1/24"
            },
            "cores": 2,
            "memory": 1024,
            "networks": ["link_a"],
            "applications": [
                {
                    "application": "ping",
                    "name": "a-ping",
                    "delay": 1,
                    "runtime": 10,
                    "settings": {
                        "target": "10.0.0.2"
                    }
                }
            ]
        },
        {
            "name": "vmb",
            "diskimage": "debian-iperf.qcow2",
            "setup_script": "setup.sh",
            "environment": {
                "IP_ADDRESS": "10.0.0.2/24"
            },
            "cores": 2,
            "memory": 1024,
            "networks": ["link_a"],
            "applications": [
                {
                    "application": "ping",
                    "name": "b-ping",
                    "delay": 1,
                    "runtime": 10,
                    "settings": {
                        "target": "10.0.0.1"
                    }
                }
            ]
        }
    ]
}

=== martin-ottens/proto2testbed/setups/sample/testbed.json
{
    "settings": {
        "management_network": "auto",
        "diskimage_basepath": "/images/"
    },
    "networks": [
        {
            "name": "exp0",
            "host_ports": []
        }
    ],
    "integrations": [
        {
            "name": "await-integration",
            "type": "await",
            "invoke_after": "startup",
            "settings": {
                "start_script": "integrations/oneshot.sh",
                "wait_for_exit": 50
            } 
        },
        {
            "name": "start-stop-integration",
            "type": "startstop",
            "invoke_after": "network",
            "wait_after_invoke": 2,
            "settings": {
                "start_delay": 5,
                "start_script": "integrations/start.sh",
                "stop_script": "integrations/stop.sh",
                "wait_for_exit": 5
            }
        },
        {
            "name": "loadable",
            "type": "integrations/loadable_integration",
            "invoke_after": "init",
            "settings": {
                "delay": 5,
                "message": "Hello from loaded integration!"
            }
        }
    ],
    "instances": [
        {
            "name": "vma",
            "diskimage": "debian.qcow2",
            "setup_script": "vma/setup.sh",
            "environment": {
                "VARIABLE": "Hello from VM A Setup!"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp0"
            ],
            "applications": [
                {
                    "application": "iperf3-server",
                    "name": "vma-iperf-server",
                    "delay": 0,
                    "runtime": null,
                    "settings": {}
                },
                {
                    "application": "procmon",
                    "name": "procmon-vma",
                    "delay": 5,
                    "runtime": 30,
                    "settings": {
                        "interfaces": ["eth1"],
                        "system": true
                    }
                },
                {
                    "application": "apps/log_app",
                    "name": "dynload_log",
                    "runtime": 30,
                    "settings": {
                        "level": "INFO",
                        "messages": [
                            "Log message one",
                            "Log message two",
                            "Log message three",
                            "Log message four",
                            "Log message five"
                        ]
                    }
                }
            ]
        },
        {
            "name": "vmb",
            "diskimage": "debian.qcow2",
            "setup_script": "vmb/setup.sh",
            "environment": {
                "VARIABLE": "Hello from VM B Setup!"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp0"
            ],
            "applications": [
                {
                    "application": "iperf3-client",
                    "name": "vmb-iperf-client",
                    "delay": 1,
                    "runtime": 30,
                    "settings": {
                        "host": "10.0.0.1"
                    },
                    "depends": [
                        {
                            "at": "started",
                            "instance": "vma",
                            "application": "vma-iperf-server"
                        }
                    ]
                },
                {
                    "application": "procmon",
                    "name": "procmon-vmb",
                    "delay": 5,
                    "runtime": 30,
                    "settings": {
                        "interfaces": ["eth1"],
                        "system": true
                    },
                    "depends": [
                        {
                            "at": "finished",
                            "instance": "vmb",
                            "application": "vmb-iperf-client"
                        }
                    ]
                },
                {
                    "application": "run-program",
                    "name": "generate-file",
                    "delay": 20,
                    "runtime": 1,
                    "settings": {
                        "command": "vmb/generate-file.sh",
                        "environment": {
                            "OUTPUT": "Generated file for vmb."
                        }
                    },
                    "depends": [
                        {
                            "at": "started",
                            "instance": "vmb",
                            "application": "procmon-vmb"
                        }
                    ]
                }
            ],
            "preserve_files": [
                "/root/output.txt"
            ]
        }
    ]
}
